### ISSUE TITLE
Input required and not supplied: github-token

### ISSUE THREAD

**Issue by codeuniquely** [IvanFon/super-labeler-action#29]
**Describe the bug**
when running the example given in the docs, in ACT,  it generates the error

**To Reproduce**
1. used the workflow and actions from this website 
2. run the workflow with `act pull_request`

**Expected behavior**
Should not error

**Config**

```json
{
  "labels": {
    "bugfix": {
      "name": "Bugfix! 🎉",
      "colour": "ff0000",
      "description": "Fixes a bug."
    }
  }
}
```

```yaml
name: Pull Request Labeler
on:
  issues: [opened, edited, closed, reopened]
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Label issues and pull requests
    steps:
      - uses: actions/checkout@v2
      - uses: IvanFon/super-labeler-action@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
```

also tried
```
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Github Actions Output**

```
[Pull Request Labeler/label-things] 🧪  Matrix: map[node-version:14.15.3 platform:ubuntu-18.04]
[Pull Request Labeler/label-things] 🚀  Start image=node:12.6-buster-slim
[Pull Request Labeler/label-things]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Pull Request Labeler/label-things]   🐳  docker cp src=/Users/steve/Projects/OPLO/. dst=/github/workspace
[Pull Request Labeler/label-things] ⭐  Run actions/checkout@v2
[Pull Request Labeler/label-things]   ✅  Success - actions/checkout@v2
[Pull Request Labeler/label-things] ⭐  Run IvanFon/super-labeler-action@v1
[Pull Request Labeler/label-things]   ☁  git clone 'https://github.com/IvanFon/super-labeler-action' # ref=v1
[Pull Request Labeler/label-things]   🐳  docker cp src=/Users/steve/.cache/act/IvanFon-super-labeler-action@v1 dst=/actions/
[Pull Request Labeler/label-things]   ❗  ::error::Input required and not supplied: github-token
[Pull Request Labeler/label-things]   ❗  ::error::Input required and not supplied: github-token
[Pull Request Labeler/label-things]   ❌  Failure - IvanFon/super-labeler-action@v1
Error: exit with `FAILURE`: 1
```
